### ISSUE TITLE
Merge does not work in case when library change notified via API by Autoscan 

### ISSUE THREAD

**Issue by sergeycherepanov** [danieladov/jellyfin-plugin-mergeversions#40]
Hi, first of all thank you for your work!

I use the [Autoscan](https://github.com/Cloudbox/autoscan) to notify Jellyfin about file changes (usually it's rename with an userformats).
But when changes applied the mergeversions plugin can't anemore merge this one.

The log of manual movies merge
```
[19:31:10] [INF] [64] Jellyfin.Api.Controllers.VideosController: Starting a manual refresh, looking up for repeated versions
[19:31:10] [INF] [64] Jellyfin.Api.Controllers.VideosController: Scanning for repeated movies
[19:31:10] [INF] [64] Jellyfin.Api.Controllers.VideosController: Completed refresh
[19:32:12] [INF] [62] Jellyfin.Api.Controllers.VideosController: Starting a manual refresh, looking up for repeated versions
[19:32:12] [INF] [62] Jellyfin.Api.Controllers.VideosController: Scanning for repeated movies
[19:32:12] [INF] [62] Jellyfin.Api.Controllers.VideosController: Completed refresh
```

<img width="784" alt="image" src="https://github.com/danieladov/jellyfin-plugin-mergeversions/assets/963777/e3787cc6-0ba5-4dda-a71d-e3b050d7b1f0">

The details. 
Version 1. 
<img width="1027" alt="image" src="https://github.com/danieladov/jellyfin-plugin-mergeversions/assets/963777/6537ad22-8a31-4cbd-a9f9-a92e05bad88b">

Version 2. 
<img width="1026" alt="image" src="https://github.com/danieladov/jellyfin-plugin-mergeversions/assets/963777/000446bf-f5e5-4f74-a95e-3d491c3a7a78">

External ids. 
Version 1. 
<img width="837" alt="image" src="https://github.com/danieladov/jellyfin-plugin-mergeversions/assets/963777/39eb6cfd-6c4d-46af-a4cd-286cb06d7518">

Version 2. 
<img width="786" alt="image" src="https://github.com/danieladov/jellyfin-plugin-mergeversions/assets/963777/759f8d3b-3eb9-4029-ae5e-185b89c96c4e">

The autoscan config:

```yaml
minimum-age: 1m
triggers:
  manual:
    priority: 5
    rewrite:
        - from: ^/Volumes/MediaLibrary/Multilang/Adult/Movies
          to: /Volumes/Merged/Adult/Movies

        - from: ^/Volumes/MediaLibrary/Ukr/Adult/Movies
          to: /Volumes/Merged/Adult/Movies

  inotify:
    - priority: 0
      include:
        - ^/Volumes/Merged
      exclude:
        - '\.(nfo|pdf)$'
      paths:
        - path: /Volumes/MediaLibrary/Multilang/Adult/Movies
        - path: /Volumes/MediaLibrary/Ukr/Adult/Movies
      rewrite:
        - from: ^/Volumes/MediaLibrary/Multilang/Adult/Movies
          to: /Volumes/Merged/Adult/Movies

        - from: ^/Volumes/MediaLibrary/Ukr/Adult/Movies
          to: /Volumes/Merged/Adult/Movies

targets:
  jellyfin:
    - url: https://example.com
      token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

I checked it on another movie and its also separated and does not merged anymore after an update trigger by Autoscan. 

I guess something wrong in case when update triggered via the Jellyfin api. 

The api request fired by Autoscan:
```bash
curl -H 'Host: jellyfin:8096' -H 'User-Agent: Go-http-client/1.1' -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'X-Emby-Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' --compressed -X POST http://jellyfin:8096/Library/Media/Updated -d '{"Updates":[{"path":"/Volumes/Merged/Adult/Movies/I, Robot (2004)","updateType":"Modified"}]}'
```
